var employees = [
{"textname":"BT_GEN_POWER_ON_CFM", "x":1, "param":["status = 0x00 ","version = 0xA001 ","supportservice = 0x0000 "]},
{"textname":"BT_GEN_SET_LOCAL_NAME_REQ", "x":0, "param":["name = 0x54070 - Bluetooth 19 ","nameLen = 0x0C "]},
{"textname":"BT_GEN_SET_LOCAL_NAME_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_GEN_SET_LOCAL_MODE_REQ", "x":0, "param":["mode = 0x6 "]},
{"textname":"BT_CM_SERVICE_CON_REQ", "x":0, "param":["function = 0x02 ","remAddr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_CM_SERVICE_CON_IND", "x":2, "param":["instanceId = 0x1 ","function = 0x02 ","status = 0x0C ","extenParam = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_COMP_IND", "x":2, "param":["function = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_REQ", "x":0, "param":["function = 0x04 ","remAddr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_REQ", "x":0, "param":["count = 0x9F ","timer = 0x1E "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_CM_SERVICE_CON_IND", "x":2, "param":["instanceId = 0x1 ","function = 0x04 ","status = 0x01 ","extenParam = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_COMP_IND", "x":2, "param":["function = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_REQ", "x":0, "param":["function = 0x08 ","remAddr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_CANCEL_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_COMP_IND", "x":2, "param":["status = 0x04 "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_REQ", "x":0, "param":["count = 0x9F ","timer = 0x1E "]},
{"textname":"BT_GEN_SEARCH_REOMTE_DEV_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_CM_SERVICE_CON_IND", "x":2, "param":["instanceId = 0x1 ","function = 0x08 ","status = 0x01 ","extenParam = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_COMP_IND", "x":2, "param":["function = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_REQ", "x":0, "param":["function = 0x10 ","remAddr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_CFM", "x":1, "param":["status = 0x00 "]},
{"textname":"BT_CM_SERVICE_CON_IND", "x":2, "param":["instanceId = 0xFF ","function = 0x10 ","status = 0x04 ","extenParam = 0x00 ","addr = 5C3C-27-6FF470 "]},
{"textname":"BT_CM_SERVICE_CON_COMP_IND", "x":2, "param":["function = 0x00 ","addr = 5C3C-27-6FF470 "]},
];